<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>MindTrail.ArchTests</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>bin\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>bin\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0"/>
        <PackageReference Include="NetArchTest.Rules" Version="1.3.2"/>
        <PackageReference Include="MSTest.TestFramework" Version="3.9.3"/>
        <PackageReference Include="MSTest.TestAdapter" Version="3.9.3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MindTrail.CliHost\MindTrail.CliHost.csproj"/>
        <ProjectReference Include="..\..\src\MindTrail.Common\MindTrail.Common.csproj"/>
        <ProjectReference Include="..\..\src\MindTrail.HostConfiguration\MindTrail.HostConfiguration.csproj"/>
        <ProjectReference Include="..\..\src\MindTrail.WebApi\MindTrail.WebApi.csproj"/>
        <ProjectReference Include="..\..\src\MindTrail.WebAuth\MindTrail.WebAuth.csproj"/>
        <ProjectReference Include="..\..\src\MindTrail.WebHost\MindTrail.WebHost.csproj"/>
    </ItemGroup>

</Project>
