<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>bin\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>bin\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Adapters\Repositories\"/>
        <Folder Include="Context\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.18" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MindTrail.DomainServices\MindTrail.DomainServices.csproj"/>
    </ItemGroup>

</Project>
