using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace MindTrail.EfCoreMssql.Migrations
{
    /// <inheritdoc />
    public partial class AddCountryTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false),
                    Code = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: false),
                    Name = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Id", "Code", "Name" },
                values: new object[,]
                {
                    { 1, "AF", "Afghanistan" },
                    { 2, "AL", "Albania" },
                    { 3, "DZ", "Algeria" },
                    { 4, "AD", "Andorra" },
                    { 5, "AO", "Angola" },
                    { 6, "AG", "Antigua and Barbuda" },
                    { 7, "AR", "Argentina" },
                    { 8, "AM", "Armenia" },
                    { 9, "AU", "Australia" },
                    { 10, "AT", "Austria" },
                    { 11, "AZ", "Azerbaijan" },
                    { 12, "BS", "Bahamas" },
                    { 13, "BH", "Bahrain" },
                    { 14, "BD", "Bangladesh" },
                    { 15, "BB", "Barbados" },
                    { 16, "BY", "Belarus" },
                    { 17, "BE", "Belgium" },
                    { 18, "BZ", "Belize" },
                    { 19, "BJ", "Benin" },
                    { 20, "BT", "Bhutan" },
                    { 21, "BO", "Bolivia" },
                    { 22, "BA", "Bosnia and Herzegovina" },
                    { 23, "BW", "Botswana" },
                    { 24, "BR", "Brazil" },
                    { 25, "BN", "Brunei" },
                    { 26, "BG", "Bulgaria" },
                    { 27, "BF", "Burkina Faso" },
                    { 28, "BI", "Burundi" },
                    { 29, "CV", "Cabo Verde" },
                    { 30, "KH", "Cambodia" },
                    { 31, "CM", "Cameroon" },
                    { 32, "CA", "Canada" },
                    { 33, "CF", "Central African Republic" },
                    { 34, "TD", "Chad" },
                    { 35, "CL", "Chile" },
                    { 36, "CN", "China" },
                    { 37, "CO", "Colombia" },
                    { 38, "KM", "Comoros" },
                    { 39, "CG", "Congo (Brazzaville)" },
                    { 40, "CD", "Congo (Kinshasa)" },
                    { 41, "CR", "Costa Rica" },
                    { 42, "HR", "Croatia" },
                    { 43, "CU", "Cuba" },
                    { 44, "CY", "Cyprus" },
                    { 45, "CZ", "Czech Republic" },
                    { 46, "DK", "Denmark" },
                    { 47, "DJ", "Djibouti" },
                    { 48, "DM", "Dominica" },
                    { 49, "DO", "Dominican Republic" },
                    { 50, "EC", "Ecuador" },
                    { 51, "EG", "Egypt" },
                    { 52, "SV", "El Salvador" },
                    { 53, "GQ", "Equatorial Guinea" },
                    { 54, "ER", "Eritrea" },
                    { 55, "EE", "Estonia" },
                    { 56, "SZ", "Eswatini" },
                    { 57, "ET", "Ethiopia" },
                    { 58, "FJ", "Fiji" },
                    { 59, "FI", "Finland" },
                    { 60, "FR", "France" },
                    { 61, "GA", "Gabon" },
                    { 62, "GM", "Gambia" },
                    { 63, "GE", "Georgia" },
                    { 64, "DE", "Germany" },
                    { 65, "GH", "Ghana" },
                    { 66, "GR", "Greece" },
                    { 67, "GD", "Grenada" },
                    { 68, "GT", "Guatemala" },
                    { 69, "GN", "Guinea" },
                    { 70, "GW", "Guinea-Bissau" },
                    { 71, "GY", "Guyana" },
                    { 72, "HT", "Haiti" },
                    { 73, "HN", "Honduras" },
                    { 74, "HU", "Hungary" },
                    { 75, "IS", "Iceland" },
                    { 76, "IN", "India" },
                    { 77, "ID", "Indonesia" },
                    { 78, "IR", "Iran" },
                    { 79, "IQ", "Iraq" },
                    { 80, "IE", "Ireland" },
                    { 81, "IL", "Israel" },
                    { 82, "IT", "Italy" },
                    { 83, "JM", "Jamaica" },
                    { 84, "JP", "Japan" },
                    { 85, "JO", "Jordan" },
                    { 86, "KZ", "Kazakhstan" },
                    { 87, "KE", "Kenya" },
                    { 88, "KI", "Kiribati" },
                    { 89, "KP", "Korea, North" },
                    { 90, "KR", "Korea, South" },
                    { 91, "XK", "Kosovo" },
                    { 92, "KW", "Kuwait" },
                    { 93, "KG", "Kyrgyzstan" },
                    { 94, "LA", "Laos" },
                    { 95, "LV", "Latvia" },
                    { 96, "LB", "Lebanon" },
                    { 97, "LS", "Lesotho" },
                    { 98, "LR", "Liberia" },
                    { 99, "LY", "Libya" },
                    { 100, "LI", "Liechtenstein" },
                    { 101, "LT", "Lithuania" },
                    { 102, "LU", "Luxembourg" },
                    { 103, "MG", "Madagascar" },
                    { 104, "MW", "Malawi" },
                    { 105, "MY", "Malaysia" },
                    { 106, "MV", "Maldives" },
                    { 107, "ML", "Mali" },
                    { 108, "MT", "Malta" },
                    { 109, "MH", "Marshall Islands" },
                    { 110, "MR", "Mauritania" },
                    { 111, "MU", "Mauritius" },
                    { 112, "MX", "Mexico" },
                    { 113, "FM", "Micronesia" },
                    { 114, "MD", "Moldova" },
                    { 115, "MC", "Monaco" },
                    { 116, "MN", "Mongolia" },
                    { 117, "ME", "Montenegro" },
                    { 118, "MA", "Morocco" },
                    { 119, "MZ", "Mozambique" },
                    { 120, "MM", "Myanmar" },
                    { 121, "NA", "Namibia" },
                    { 122, "NR", "Nauru" },
                    { 123, "NP", "Nepal" },
                    { 124, "NL", "Netherlands" },
                    { 125, "NZ", "New Zealand" },
                    { 126, "NI", "Nicaragua" },
                    { 127, "NE", "Niger" },
                    { 128, "NG", "Nigeria" },
                    { 129, "MK", "North Macedonia" },
                    { 130, "NO", "Norway" },
                    { 131, "OM", "Oman" },
                    { 132, "PK", "Pakistan" },
                    { 133, "PW", "Palau" },
                    { 134, "PS", "Palestine" },
                    { 135, "PA", "Panama" },
                    { 136, "PG", "Papua New Guinea" },
                    { 137, "PY", "Paraguay" },
                    { 138, "PE", "Peru" },
                    { 139, "PH", "Philippines" },
                    { 140, "PL", "Poland" },
                    { 141, "PT", "Portugal" },
                    { 142, "QA", "Qatar" },
                    { 143, "RO", "Romania" },
                    { 144, "RU", "Russia" },
                    { 145, "RW", "Rwanda" },
                    { 146, "KN", "Saint Kitts and Nevis" },
                    { 147, "LC", "Saint Lucia" },
                    { 148, "VC", "Saint Vincent and the Grenadines" },
                    { 149, "WS", "Samoa" },
                    { 150, "SM", "San Marino" },
                    { 151, "ST", "Sao Tome and Principe" },
                    { 152, "SA", "Saudi Arabia" },
                    { 153, "SN", "Senegal" },
                    { 154, "RS", "Serbia" },
                    { 155, "SC", "Seychelles" },
                    { 156, "SL", "Sierra Leone" },
                    { 157, "SG", "Singapore" },
                    { 158, "SK", "Slovakia" },
                    { 159, "SI", "Slovenia" },
                    { 160, "SB", "Solomon Islands" },
                    { 161, "SO", "Somalia" },
                    { 162, "ZA", "South Africa" },
                    { 163, "SS", "South Sudan" },
                    { 164, "ES", "Spain" },
                    { 165, "LK", "Sri Lanka" },
                    { 166, "SD", "Sudan" },
                    { 167, "SR", "Suriname" },
                    { 168, "SE", "Sweden" },
                    { 169, "CH", "Switzerland" },
                    { 170, "SY", "Syria" },
                    { 171, "TW", "Taiwan" },
                    { 172, "TJ", "Tajikistan" },
                    { 173, "TZ", "Tanzania" },
                    { 174, "TH", "Thailand" },
                    { 175, "TL", "Timor-Leste" },
                    { 176, "TG", "Togo" },
                    { 177, "TO", "Tonga" },
                    { 178, "TT", "Trinidad and Tobago" },
                    { 179, "TN", "Tunisia" },
                    { 180, "TR", "Turkey" },
                    { 181, "TM", "Turkmenistan" },
                    { 182, "TV", "Tuvalu" },
                    { 183, "UG", "Uganda" },
                    { 184, "UA", "Ukraine" },
                    { 185, "AE", "United Arab Emirates" },
                    { 186, "GB", "United Kingdom" },
                    { 187, "US", "United States" },
                    { 188, "UY", "Uruguay" },
                    { 189, "UZ", "Uzbekistan" },
                    { 190, "VU", "Vanuatu" },
                    { 191, "VA", "Vatican City" },
                    { 192, "VE", "Venezuela" },
                    { 193, "VN", "Vietnam" },
                    { 194, "YE", "Yemen" },
                    { 195, "ZM", "Zambia" },
                    { 196, "ZW", "Zimbabwe" },
                    { 197, "AQ", "Akrotiri and Dhekelia" },
                    { 198, "AS", "American Samoa" },
                    { 199, "AI", "Anguilla" },
                    { 200, "AW", "Aruba" },
                    { 201, "BM", "Bermuda" },
                    { 202, "BQ", "Bonaire, Sint Eustatius and Saba" },
                    { 203, "IO", "British Indian Ocean Territory" },
                    { 204, "VG", "British Virgin Islands" },
                    { 205, "KY", "Cayman Islands" },
                    { 206, "CX", "Christmas Island" },
                    { 207, "CC", "Cocos (Keeling) Islands" },
                    { 208, "CK", "Cook Islands" },
                    { 209, "CW", "Curacao" },
                    { 210, "FO", "Faroe Islands" },
                    { 211, "GF", "French Guiana" },
                    { 212, "PF", "French Polynesia" },
                    { 213, "TF", "French Southern Territories" },
                    { 214, "GI", "Gibraltar" },
                    { 215, "GL", "Greenland" },
                    { 216, "GP", "Guadeloupe" },
                    { 217, "GU", "Guam" },
                    { 218, "HK", "Hong Kong" },
                    { 219, "MO", "Macau" },
                    { 220, "MQ", "Martinique" },
                    { 221, "YT", "Mayotte" },
                    { 222, "MS", "Montserrat" },
                    { 223, "NC", "New Caledonia" },
                    { 224, "MP", "Northern Mariana Islands" },
                    { 225, "PR", "Puerto Rico" },
                    { 226, "RE", "Reunion" },
                    { 227, "BL", "Saint Barthelemy" },
                    { 228, "MF", "Saint Martin" },
                    { 229, "PM", "Saint Pierre and Miquelon" },
                    { 230, "SX", "Sint Maarten" },
                    { 231, "TK", "Tokelau" },
                    { 232, "TC", "Turks and Caicos Islands" },
                    { 233, "VI", "United States Virgin Islands" },
                    { 234, "WF", "Wallis and Futuna" },
                    { 235, "AX", "Åland Islands" },
                    { 236, "HM", "Heard Island and McDonald Islands" },
                    { 237, "CI", "Côte d'Ivoire" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Countries_Code",
                table: "Countries",
                column: "Code",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Countries");
        }
    }
}
