<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>bin\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>bin\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MindTrail.AppServices\MindTrail.AppServices.csproj" />
        <ProjectReference Include="..\MindTrail.Common\MindTrail.Common.csproj" />
        <ProjectReference Include="..\MindTrail.WebAuth\MindTrail.WebAuth.csproj" />
    </ItemGroup>

</Project>
